#!/usr/bin/env python3

from __future__ import annotations

import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
REGISTRY_ROOT = REPO_ROOT / "integrations" / "registry"
DIST_ROOT = REPO_ROOT / "integrations" / "dist"


def _load_manifests(kind: str) -> list[dict]:
    items: list[dict] = []
    for path in sorted((REGISTRY_ROOT / kind).glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        data["_source"] = str(path.relative_to(REPO_ROOT))
        items.append(data)
    return items


def _validate(manifest: dict, expected_kind: str) -> None:
    if manifest.get("kind") != expected_kind.rstrip("s"):
        raise ValueError(f"{manifest.get('_source')}: expected kind {expected_kind.rstrip('s')}")
    if not manifest.get("id"):
        raise ValueError(f"{manifest.get('_source')}: missing id")


def _render_catalog(skills: list[dict], mcps: list[dict], gateways: list[dict]) -> dict:
    return {
        "version": 1,
        "generatedFrom": "scripts/render_integrations.py",
        "skills": skills,
        "mcpServers": mcps,
        "modelGateways": gateways,
    }


def _render_deerflow_extensions(mcps: list[dict]) -> dict:
    rendered = {"mcpServers": {}, "skills": {}}
    for manifest in mcps:
        deerflow = (manifest.get("targets") or {}).get("deerflow") or {}
        name = deerflow.get("server_name") or manifest["id"]
        transport = manifest.get("transport") or {}
        rendered["mcpServers"][name] = {
            "enabled": bool(manifest.get("enabled_by_default", False)),
            "type": transport.get("type", "stdio"),
            "command": transport.get("command", ""),
            "args": transport.get("args", []),
            "env": transport.get("env", {}),
            "description": manifest.get("description", ""),
        }
    return rendered


def _render_deerflow_models_yaml(gateways: list[dict]) -> str:
    lines = [
        "# Generated by scripts/render_integrations.py",
        "models:",
    ]
    for gateway in gateways:
        for model in gateway.get("models") or []:
            api_key_env = model.get("api_key_env") or "QWENPOOL_API_KEY"
            fallback = model.get("api_key_fallback") or "sk-dummy"
            lines.extend(
                [
                    f"  - name: {model['name']}",
                    f"    display_name: {model.get('display_name', model['name'])}",
                    "    use: langchain_openai:ChatOpenAI",
                    f"    model: {model['provider_model']}",
                    f"    api_key: ${api_key_env}:{fallback}",
                    f"    base_url: {gateway['base_url']}",
                    f"    max_tokens: {model.get('max_tokens', 4096)}",
                    f"    temperature: {model.get('temperature', 0.7)}",
                    f"    supports_thinking: {str(bool(model.get('supports_thinking', False))).lower()}",
                    f"    supports_vision: {str(bool(model.get('supports_vision', False))).lower()}",
                ]
            )
    return "\n".join(lines) + "\n"


def main() -> None:
    skills = _load_manifests("skills")
    mcps = _load_manifests("mcp")
    gateways = _load_manifests("model_gateways")

    for item in skills:
        _validate(item, "skills")
    for item in mcps:
        _validate(item, "mcp")
    for item in gateways:
        _validate(item, "model_gateways")

    (DIST_ROOT / "deerflow").mkdir(parents=True, exist_ok=True)

    catalog = _render_catalog(skills, mcps, gateways)
    (DIST_ROOT / "catalog.json").write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    deerflow_extensions = _render_deerflow_extensions(mcps)
    (DIST_ROOT / "deerflow" / "extensions_config.generated.json").write_text(
        json.dumps(deerflow_extensions, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    deerflow_models_yaml = _render_deerflow_models_yaml(gateways)
    (DIST_ROOT / "deerflow" / "models.generated.yaml").write_text(deerflow_models_yaml, encoding="utf-8")

    print("Rendered integrations registry outputs:")
    print(f"- {(DIST_ROOT / 'catalog.json').relative_to(REPO_ROOT)}")
    print(f"- {(DIST_ROOT / 'deerflow' / 'extensions_config.generated.json').relative_to(REPO_ROOT)}")
    print(f"- {(DIST_ROOT / 'deerflow' / 'models.generated.yaml').relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
